/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package School;


import java.awt.Color;
import javax.swing.*;
import java.util.*;
import java.io.*;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.time.LocalDateTime;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
//import net.proteanit.sql.DbUtils;




/**
 *
 * @author sibab
 */
public class Details extends javax.swing.JFrame  {
    
    
    
   Connection con;
    PreparedStatement pst;
    ResultSet rs;
    public String  UserID;
  
    
    int i,q;
    public User playerDetails;
    
    
    
    
    

    /**
     * Creates new form Details
     */
    public Details() {
        initComponents();
        
     
    }
    
    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtSurname = new javax.swing.JTextField();
        txtUserID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        lblMainError = new javax.swing.JLabel();
        lblMainError2 = new javax.swing.JLabel();
        lblNameError = new javax.swing.JLabel();
        lblSurnameError = new javax.swing.JLabel();
        lblAgeError = new javax.swing.JLabel();
        lblUserIDError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Details Page ");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("User Login ");

        jLabel2.setText("Name: ");

        jLabel3.setText("Surname: ");

        jLabel4.setText("UserID: ");

        txtName.setText("Please Enter Your Name");
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtSurname.setText("Please Enter Your Surname");
        txtSurname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSurnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSurnameFocusLost(evt);
            }
        });

        txtUserID.setText("Please Enter Your UserID");
        txtUserID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserIDFocusLost(evt);
            }
        });

        jButton1.setText("Save ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Age: ");

        txtAge.setText("Please Enter Your Age");
        txtAge.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAgeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAgeFocusLost(evt);
            }
        });

        jButton2.setText("Exit ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblMainError.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMainError.setForeground(new java.awt.Color(255, 0, 0));

        lblMainError2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMainError2.setForeground(new java.awt.Color(255, 0, 0));

        lblNameError.setForeground(new java.awt.Color(255, 0, 0));

        lblSurnameError.setForeground(new java.awt.Color(255, 0, 0));

        lblAgeError.setForeground(new java.awt.Color(255, 0, 0));

        lblUserIDError.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName)
                            .addComponent(txtSurname, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSurnameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtAge, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUserID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUserIDError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAgeError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMainError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMainError2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton2))
                .addGap(13, 13, 13)
                .addComponent(lblMainError)
                .addGap(32, 32, 32)
                .addComponent(lblMainError2)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNameError))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSurnameError)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAgeError))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserIDError)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void txtNameFocusGained(java.awt.event.FocusEvent evt) {                                    
      
        if(txtName.getText().equals("Please Enter Your Name"))
        {
            txtName.setText("");
            txtName.setForeground(new Color(153,153,153)); 
        }
    }                                   

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {                                  
        if(txtName.getText().equals(""))
        {
            txtName.setText("Please Enter Your Name");
            txtName.setForeground(new Color(153,153,153));
        }
    }                                 

    private void txtSurnameFocusGained(java.awt.event.FocusEvent evt) {                                       
     
        if(txtSurname.getText().equals("Please Enter Your Surname"))
        {
            txtSurname.setText("");
            txtSurname.setForeground(new Color(153,153,153)); 
        }
    }                                      

    private void txtSurnameFocusLost(java.awt.event.FocusEvent evt) {                                     
        
        if(txtSurname.getText().equals(""))
        {
            txtSurname.setText("Please Enter Your Surname");
            txtSurname.setForeground(new Color(153,153,153)); 
        }
        
        
    }                                    

    private void txtAgeFocusGained(java.awt.event.FocusEvent evt) {                                   
       
        if(txtAge.getText().equals("Please Enter Your Age"))
        {
            txtAge.setText("");
            txtAge.setForeground(new Color(153,153,153)); 
        }
    }                                  

    private void txtAgeFocusLost(java.awt.event.FocusEvent evt) {                                 
       
        if(txtAge.getText().equals(""))
        {
            txtAge.setText("Please Enter Your Age");
            txtAge.setForeground(new Color(153,153,153)); 
        }
    }                                

    private void txtUserIDFocusGained(java.awt.event.FocusEvent evt) {                                      
        
      if(txtUserID.getText().equals("Please Enter Your UserID"))
        {
            txtUserID.setText("");
            txtUserID.setForeground(new Color(153,153,153)); 
        }  
    }                                     

    private void txtUserIDFocusLost(java.awt.event.FocusEvent evt) {                                    
      
       if(txtUserID.getText().equals(""))
        {
            txtUserID.setText("Please Enter Your UserID");
            txtUserID.setForeground(new Color(153,153,153)); 
        } 
    }                                   

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
        System.exit(0);
    }                                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
        String name = txtName.getText().trim();
        String surname = txtSurname.getText().trim();
        String ageString = txtAge.getText().trim();
        String userID = txtUserID.getText().trim();
        boolean correctInput = true;
        
        
        
        lblMainError.setText("");
        lblMainError2.setText("");
        lblNameError.setText("");
        lblSurnameError.setText("");
        lblAgeError.setText("");
        lblUserIDError.setText("");
        
        Boolean checkFilled = true;
        
        if(name.equals("") || name.equals("Please Enter Your Name"))
        {
            lblMainError.setText("There is a section that was left blank");
            lblNameError.setText("Please fill in");
            checkFilled = false;
            correctInput = false;
        }
        
          if(surname.equals("") || name.equals("Please Enter Your Name"))
        {
            lblMainError.setText("There is a section that was left blank");
            lblNameError.setText("Please fill in");
            checkFilled = false;
            correctInput = false;
        }
        
        if(ageString.equals("") || ageString.equals("Please Enter Your Age"))
        {
            lblMainError.setText("There is a section that was left blank");
            lblAgeError.setText("Please fil in");
            checkFilled = false;
            correctInput = false;
        }
        
        if(userID.equals("") || userID.equals("Please Enter Your Name"))
        {
            lblMainError.setText("There is a section that was left blank");
            lblUserIDError.setText("Please fill in");
            checkFilled = false;
            correctInput = false;
        }
            
         if(checkFilled = true)
         {
             boolean intFailed = false;
             boolean stringFailed = false;
             
             try
             {
                int age =  Integer.parseInt(ageString);
             }
             catch(NumberFormatException e)
             {
                txtAge.setText("Please Enter Your Age");
                lblMainError.setText("Please Enter Digits Only for Age. Do not use Digis for Name and Surname.");
                lblAgeError.setText("Use Digits Only");
                intFailed = true;
                correctInput = false;
                
             }
             
             Test nameTest = new Test(name);
             Test surnameTest = new Test(surname);
             Test ageTest = new Test(Integer.parseInt(ageString));
             
             
             
             if(nameTest.hasDigits() == true)
             {
                 txtName.setText("Please Enter Your Name");
                 lblMainError.setText("Please Enter Digits Only for Age. Do not use Digis for Name and Surname.");
                 lblNameError.setText("Use Digits Only");
                 stringFailed = true;
                 correctInput = false;
                 
                 
             }
             
             if(surnameTest.hasDigits() == true)
             {
                 txtSurname.setText("Please Enter Your Surname");
                 lblMainError.setText("Please Enter Digits Only for Age. Do not use Digis for Name and Surname.");
                 lblSurnameError.setText("Use Digits Only");
                 stringFailed = true;
                 correctInput = false;
             }
            
             if(intFailed = false && stringFailed == false)
             {
                 if(nameTest.checkLength() == true)
                 {
                    txtName.setText("Please Enter Your Name");
                    lblMainError.setText("Please Enter Between 2 and 25 letters only");
                    lblNameError.setText("Input too long or short"); 
                    correctInput = false;
                   
                 }
                 
                 if(surnameTest.checkLength() == true)
                 {
                     txtSurname.setText("Please Enter Your Surname");
                     lblMainError.setText("Please Enter Between 2 and 25 letters only");
                     lblSurnameError.setText("Input too long or short");
                     correctInput = false;
                 }
                 
                 if(ageTest.checkAge() == true)
                 {
                     txtAge.setText("Please Enter Your Age");
                     lblMainError2.setText("Age cannot be negative or exceed 120");
                     lblAgeError.setText("Invalid Input");
                     correctInput = false;
                 }
             }
             
         }
         boolean loginSuccess = false;
         
         if(correctInput == true)
         {
             int userAge = Integer.parseInt(txtAge.getText().trim());
             
             Connection con = null;
             PreparedStatement pst = null;
             ResultSet rs = null;
             
             try
             {
                 Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                 con = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\sibab\\Downloads\\Lotterydb.accdb");
                 String sql = "Select * from Userdb where UserID = '" + txtUserID.getText() + "' ";
                 pst = con.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
                 rs = pst.executeQuery();
                 if(rs.next())
                 {
                     JOptionPane.showMessageDialog(null, "Login Success");
                     userID = rs.getString(1);
                     loginSuccess = true;
                    String intoName = txtName.getText();
                    String intoSurname = txtSurname.getText();
                    int intoAge = (int) Integer.parseInt(txtAge.getText());
                    
                     System.out.println(userID);
                     System.out.println(intoName);
                     System.out.println(intoSurname);
                     System.out.println(intoAge);
                    
                    User playerDetails = new User(intoName, intoSurname, intoAge , userID);
                    
                    
                    
                   
                     
                     
                 }
                
                     
                  
                 
                 
             }
             catch(Exception e )
             {
               JFrame frame;
                  frame = new JFrame("Add User");
                     
                  if(JOptionPane.showConfirmDialog(frame, "Add user to database ", "Add User", 
                     JOptionPane.YES_NO_CANCEL_OPTION) == JOptionPane.YES_NO_OPTION)
                     {
                        try
                        {
                           con = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\sibab\\Downloads\\Lotterydb.accdb");
                            Statement st = con.createStatement();
                            
                             String intoName = txtName.getText();
                             String intoSurname = txtSurname.getText();
                             int intoAge = (int) Integer.parseInt(txtAge.getText());
                            
                             LocalDateTime currentDateTime = LocalDateTime.now();
                             
                             
        
                            int year = currentDateTime.getYear();
                            int month = currentDateTime.getMonthValue();
                            int day = currentDateTime.getDayOfMonth();
       
       
                            String intoDate = "#" + year + "-" + month + "-" + day + "#";
                            
                            String sql = "Insert into Userdb " + "(Name, Surname, Age, RegistrationDate)" + 
                                    "values("  + "'"+ intoName + "','" + intoSurname + "'," + intoAge + "," + intoDate +  ");";
                            
                         
                           
                            
                            
                                    
                            
                            
                         PreparedStatement pst2 = con.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
                         
                         int a = pst2.executeUpdate();
                            
                         
                          
                            
                            if(a  == 1)
                            {
                                JOptionPane.showMessageDialog(this, "New User Added.\n Welcome" );
                                 ResultSet rs2 = pst2.getGeneratedKeys();
                                 
                                 if(rs2.next())
                                 {
                                  String intoUserID = rs2.getString(1);
                                   System.out.println(userID);
                                   loginSuccess = true;
                                
                                   User playerDetails = new User(intoName, intoSurname , intoAge, intoUserID);
                                   
                                     
                                  
                                 }
                                  
                            }else
                            {
                                JOptionPane.showMessageDialog(this, "Error inserting data");
                            }
                            
                        }
                        catch(Exception ex)
                        {
                            JOptionPane.showMessageDialog(null, ex);
                            System.out.println(ex);
                        }
                 
             }
              else
             {
                 JOptionPane.showMessageDialog(null, "Invalid UserID.\nYou need to create a userID before you proceed");
             }
             
                     
             
             
             
              
          
            
         }
         }
        if(loginSuccess == true)
        {
             new TicketUI().setVisible(true); 
             new Results().setVisible(true);
             new UpdateTicket().setVisible(true);
             
        }
       
                                   
       
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblAgeError;
    private javax.swing.JLabel lblMainError;
    private javax.swing.JLabel lblMainError2;
    private javax.swing.JLabel lblNameError;
    private javax.swing.JLabel lblSurnameError;
    private javax.swing.JLabel lblUserIDError;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSurname;
    private javax.swing.JTextField txtUserID;
    // End of variables declaration                   
}
